### ISSUE TITLE
Can't set size of an image

### ISSUE THREAD

**Issue by afrantz** [edi9999/docxtemplater-image-module#1]
Hello,

I would like set the size of an image, so as you said i wrote this :

>imageModule=new ImageModule({centered:false})
>imageModule.getSizeFromData=function(imgData) {
>   console.log('ok');
>   sizeOf=require('image-size');
>   sizeObj=sizeOf(imgData);
>   console.log(sizeObj);
>   return [sizeObj.width,sizeObj.height];
>}

This doesn't work for me, the function "getSizeFromData" is never called and my image stay with the default size.

Thank you in advance and sorry for my poor english.
Alex.

**Comment by afrantz** [comment]
Sorry for the inconvenience, I work on 2 computers and I forgotten npm update...

**Comment by edi9999** [comment]
Great to see self-closing issues :-)
