### ISSUE TITLE
Images from stream

### ISSUE THREAD

**Issue by DirkStevens** [edi9999/docxtemplater-image-module#3]
Dear @edi9999 - thanks for a wonderful library!

Is it possible to provide image data as a binary stream?

**Comment by edi9999** [comment]
Hi @DirkStevens,

I would be glad to make that possible. Can you maybe work on a pull request ?


Here's how I load the file now: https://github.com/edi9999/docxtemplater-image-module/blob/master/coffee/index.coffee#L45

However, you could write an async method instead.

Also, the imagqrcode module would have to return a promise instead probably.

**Comment by DirkStevens** [comment]
Great @edi9999 !

Not sure what you mean with working on a pull request?

**Comment by edi9999** [comment]
On the top of the page, you can click on a fork button, where you can then publish your own changes. From there on, if you push some changes, you can create a "Pull request" which will make it possible for me to apply your changes.

**Comment by DirkStevens** [comment]
Hello @edi9999 - could you reach out to me via mail (see my profile) ?
