### ISSUE TITLE
Missing jszip dependency?

### ISSUE THREAD

**Issue by CowboyCoderForever** [edi9999/docxtemplater-image-module#4]
Using a package.json with:
"dependencies": {
    "docxtemplater": "latest",
    "docxtemplater-image-module": "latest"
}

...and a JS of:
var templater = require('docxtemplater');
var imageModule = require('docxtemplater-image-module');

...results in:
"  Error: Cannot find module 'jszip'" when running.

Adding "jszip": "^2.4.0" to the dependencies of the docxtemplater-image-module package.json seems to fix the problem.

Thanks!

**Comment by edi9999** [comment]
yes it is used in docxqrcode file. I will add the dependency

**Comment by edi9999** [comment]
I've fixed this now. Thanks for giving the information :-)
